name: 'Bon courage'
on: [push]
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: YESes
          title: 'TEST'
          labels: |
            bug
          assignees: ${{ github.actor }}




#    - name: Create Pull Request
#        id: cpr
#        uses: peter-evans/create-pull-request@v5
#
#        - name: Create or Update Project Card
#          if: ${{ steps.cpr.outputs.pull-request-number }}
#          uses: peter-evans/create-or-update-project-card@v2
#          with:
#            project-name: My project
#            column-name: My column
#            issue-number: ${{ steps.cpr.outputs.pull-request-number }}
